### ISSUE TITLE
[BUG] Alsa dependency requirement for Amethyst 'server' feature

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [amethyst/amethyst#2490] opened 2020-09-20 01:45 UTC
## Description

I want to use only `server` feature from Amethyst. So I added the following lines into a `Cargo.toml`
```
[dependencies.amethyst]
version = "0.15.3"
default-features = false
features = ["empty", "server"]
```

## What You Expected to Happen

Successful build without requirements for Alsa devel headers.

## What Actually Happened

Build failed with a message about some build errors for `alsa-sys` package. After installing required dependency build become succesful.

## Screenshots and Logs

Sorry, I didn't saved logs for the issue :(

## Your Environment

1. Operating System: Fedora
2. Operating System Version: 32
3. Version of Amethyst: 0.15.3

## Additional Context
Seems like that's not a single issue about extra dependencies. Is it possible to build `amethyst` completely for server side with no GUI at all?

**Comment by UgurcanAkkok** [comment] 2020-09-27 09:40
It looks like amethyst_ui is not optional. and it fetches the dependencies as shown here 
```
├── amethyst_ui v0.15.3
│   ├── amethyst_assets v0.15.3 (*)
│   ├── amethyst_audio v0.15.3
│   │   ├── amethyst_assets v0.15.3 (*)
│   │   ├── amethyst_core v0.15.3 (*)
│   │   ├── amethyst_error v0.15.3 (*)
│   │   ├── cpal v0.11.0
│   │   │   ├── alsa-sys v0.1.2
│   │   │   │   └── libc v0.2.77
```
This is from the output of `cargo tree` with the same configuration of Cargo.toml as @ZaMaZaN4iK

**Comment by UgurcanAkkok** [comment] 2020-09-27 09:58
I tried to make it optional with changing Cargo.toml of Amethyst like this:
```
[features]
default = ["animation", "audio", "locale", "network", "renderer", "ui"]
// ...
ui = [
    "amethyst_ui",
]
// ...
[dependencies]
amethyst_ui = { path = "amethyst_ui", version = "0.15.3", optional = true}
```
And then in an empty project fetched that amethyst repo as dependency with the same configuration as authors. But this file uses ui module "..../amethyst/src/state_event.rs:12:5".

Can we put that behind a feature flag and make ui a default but optional feature? I think that would solve the problem.

**Comment by CleanCut** [comment] 2020-09-28 02:57
Duplicate of https://github.com/amethyst/amethyst/issues/2193, but I'm going to leave this open as it has a better discussion.

> Can we put that behind a feature flag and make ui a default but optional feature? I think that would solve the problem.

@UgurcanAkkok My guess is yes, though I can't be certain.  The only sub-crate that I see depending on `amethyst_ui` is `amethyst_animation`, which is itself an optional crate included by default.  Would you like to try making the change? I'd be happy to review your pull request.

**Comment by UgurcanAkkok** [comment] 2020-09-28 09:55
Yes I would be happy to help. I am not super familiar with the codebase but i will see what i can do.

**Comment by ZaMaZaN4iK** [comment] 2020-10-02 15:32
Hi! I've tried a little bit to mark all dependencies as optional and enable them as features. Unfortunately, that's not so easy to do since `amethyst_ui` is directly used in some generic `amethyst` code. Here is my attempt: https://github.com/ZaMaZaN4iK/amethyst

**Closed** 2020-11-15 11:42 UTC
Labels: status: needs triage, type: bug
