### ISSUE TITLE
All the examples have window problems

### ISSUE THREAD

**Issue by ddewert** [amethyst/amethyst#492] opened 2017-11-20 02:47 UTC
Window content is not resized when resizing the window, and the border is drawn wrong.
I'm using Ubuntu 17.10 with Mesa drivers.

I believe the issue is with Glutin. I'm having the same problem with Piston, which goes away if I use SDL2.
![screenshot from 2017-11-19 18-40-57](https://user-images.githubusercontent.com/10677230/32999922-cfdfff86-cd59-11e7-903e-bb37e9896985.png)

**Comment by Xaeroxe** [comment] 2017-11-20 05:11
I will certainly attempt to reproduce this.  I've been a pretty regular Linux Mint user myself and haven't observed this.  That's some strange behavior.

**Comment by ddewert** [comment] 2017-11-22 18:21
Thanks for the tip about Mint. The best I can do with Ubuntu 17.10 is use Piston/SDL. It seems like the current consensus is that Glutin is the best hope for the future? I'm new to Rust, out of curiosity, is there much interest in SDL?

**Comment by Xaeroxe** [comment] 2017-11-22 18:24
@ddewert > Is there much interest in SDL?

Depends on who you ask.  I think the general consensus right now is that SDL2 is much more powerful and reliable, but also flawed and imperfect in many ways that we can't correct in C/C++.

**Comment by Binero** [comment] 2017-11-22 18:26
This is a Wayland issue, also exists in GFX. https://github.com/gfx-rs/gfx/issues/1217

**Comment by gotocoffee1** [comment] 2017-11-24 21:04
`std::env::set_var("WINIT_UNIX_BACKEND", "x11");` fixes it for me, I also had to set multisampling to 0

**Comment by Xaeroxe** [comment] 2017-11-28 05:05
I'm closing this since there isn't really anything in this code base responsible for this.

**Closed** 2017-11-28 05:05 UTC
Labels: diff: medium, note: help wanted, project: rendering, type: bug

**Comment by ddewert** [comment] 2017-11-28 14:21
This was helpful:
https://github.com/tomaka/winit/issues/306

**Comment by ddewert** [comment] 2017-11-28 15:08
So for those completely new to amethyst and Rust (as I am) who are also enjoying Ubuntu 17.10:
To make the sphere example work, for instance:

Find the line in main.rs that says:

`fn run() -> Result<(), amethyst::Error> {`

change it to:
```
fn run() -> Result<(), amethyst::Error> {
    std::env::set_var("WINIT_UNIX_BACKEND", "x11");
```
Find the line in `examples/sphere/resources/display_config.ron` that says `multisampling: 1` and change that to `multisampleing: 0`

This works for me.

**Comment by Rhuagh** [comment] 2017-11-28 15:11
Why not just do `WINIT_UNIX_BACKEND=x11 cargo run.. `

**Comment by ddewert** [comment] 2017-11-28 16:10
Ha!
