### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by ergpopler** [amethyst/amethyst#2482] opened 2020-09-08 01:02 UTC
## Description

[INFO][amethyst::app] Initializing Amethyst...
[INFO][amethyst::app] Version: 0.15.3
[INFO][amethyst::app] Platform: x86_64-unknown-linux-gnu
[INFO][amethyst::app] Amethyst git commit: UNKNOWN
[INFO][amethyst::app] Rustc version: 1.46.0 Stable
[INFO][amethyst::app] Rustc git commit: 04488afe34512aa4c33566eb16d8c912a3ae04f9
[INFO][winit::platform::platform::x11::window] Guessed window DPI factor: 1.001312255859375
[WARN][gfx_backend_vulkan] Unable to find layer: VK_LAYER_LUNARG_standard_validation
[WARN][rendy_factory::factory] Slow safety checks are enabled! Disable them in production by enabling the 'no-slow-safety-checks' feature!
[ERROR][gfx_backend_vulkan] 
GENERAL [Loader Message (0)] : setupLoaderTermPhysDevs:  Failed to detect any valid GPUs in the current config
object info: (type: INSTANCE, hndl: 94359265200176)

[ERROR][gfx_backend_vulkan] 
GENERAL [Loader Message (0)] : setupLoaderTrampPhysDevs:  Failed during dispatch call of 'vkEnumeratePhysicalDevices' to lower layers or loader to get count.
object info: (type: INSTANCE, hndl: 94359265200176)

[ERROR][gfx_backend_vulkan] 
GENERAL [Loader Message (0)] : setupLoaderTermPhysDevs:  Failed to detect any valid GPUs in the current config
object info: (type: INSTANCE, hndl: 94359265200176)

[ERROR][gfx_backend_vulkan] 
GENERAL [Loader Message (0)] : setupLoaderTrampPhysDevs:  Failed during dispatch call of 'vkEnumeratePhysicalDevices' to lower layers or loader to get count.
object info: (type: INSTANCE, hndl: 94359265200176)

[ERROR][gfx_backend_vulkan] Could not enumerate physical devices! Initialization of a object has failed
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorMessage { msg: "No physical devices found" }', /home/parrot/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst_rendy-0.15.3/src/system.rs:148:81
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace 
          

error: aborting due to previous error; 3 warnings emitted

error: could not compile `Amethyst`.

`use amethyst::{
    prelude::*,
    renderer::{
        plugins::{RenderFlat2D, RenderToWindow},
        types::DefaultBackend,
        RenderingBundle,
    },
    utils::application_root_dir,
};

pub struct Pong;

impl SimpleState for Pong {}

fn main() -> amethyst::Result<()> {
    amethyst::start_logger(Default::default());

    let app_root = application_root_dir()?;
    let display_config_path = app_root.join("config").join("display.ron");

    // This line is not mentioned in the pong tutorial as it is specific to the context
    // of the git repository. It only is a different location to load the assets from.
    let assets_dir = app_root.join("assets");

    let game_data = GameDataBuilder::default().with_bundle(
        RenderingBundle::<DefaultBackend>::new()
            // The RenderToWindow plugin provides all the scaffolding for opening a window and
            // drawing on it
            .with_plugin(
                RenderToWindow::from_config_path(display_config_path)?
                    .with_clear([0.0, 0.0, 0.0, 1.0]),
            )
            // RenderFlat2D plugin is used to render entities with `SpriteRender` component.
            .with_plugin(RenderFlat2D::default()),
    )?;

    let mut game = Application::new(assets_dir, Pong, game_data)?;
    game.run();
    Ok(())
    }`

## What You Expected to Happen

Whatever the Pong tutorial from the Amethyst book would do at this point ( it said to compile)

## What Actually Happened
this error

## Screenshots and Logs

If applicable, add screenshots to help explain your problem. Any relevant logs would be helpful as well.

## Your Environment

1. Linux
2. Debian
3. 15

**Comment by 0x6273** [comment] 2020-09-08 04:30
Duplicate of #1471. You need to install the dependencies that are listed in the [README.md](https://github.com/amethyst/amethyst/blob/master/README.md).

**Comment by ergpopler** [comment] 2020-09-08 22:08
yeah, I did. Still get this error

**Comment by 0x6273** [comment] 2020-09-09 03:22
Seems like you edited your issue with a completely different error? This one is likely caused by missing graphics drivers, or an unsupported (really old) GPU. Could you post the output of `vulkaninfo`?

**Comment by jojolepro** [comment] 2020-09-25 14:02
You need a semi-recent graphics card as well as graphics drivers installed.

**Closed by jojolepro** 2020-09-25 14:02 UTC
Labels: status: needs triage, type: bug
