### ISSUE TITLE
Segmentation faults on mouse events

### ISSUE THREAD

**Issue by Binero** [amethyst/amethyst#156] opened 2017-01-10 01:08 UTC
Going from the /examples, the library segfault when a mouse enters any window generated by it. I tested on release mode and debug mode, on all the examples. The only one which isn't affected, of course, is hello world. 

I am running a Vulkan capable intel driver, on a Wayland based desktop environment.

**Comment by kvark** [comment] 2017-01-10 02:46
I get this too on Intel/Wayland. I thought that's just because of the rough Wayland implementation and didn't go further investigating it. It might as well be something we are doing? Might be worth checking how other projects behave.

**Comment by Binero** [comment] 2017-01-10 09:45
I don't have this issue with Vulkano, GFX or Glium. The issue seems to be unique for Amethyst.

**Comment by kvark** [comment] 2017-01-10 12:56
Well, I do see it on Gfx-rs. Could you double-check? Maybe it's something in glutin that was resolved semi-recently, and Amethyst is using an old Gfx-/glutin version.

**Comment by Binero** [comment] 2017-01-10 22:40
It's an issue with gfx-rs 0.10 which this crate still uses. Once it's updated to the latest version it should be resolved.

**Comment by ebkalderon** [comment] 2017-02-06 05:46
We are currently using `gfx` 0.12.X at the time of this writing. Are the segfaults still occurring?

**Comment by Binero** [comment] 2017-02-06 14:19
Still segfaults. Tried on pong in both debug and release. Same symptoms.

**Comment by ebkalderon** [comment] 2017-02-06 14:28
Very strange. I still can't reproduce this on my laptop. I'm running GNOME/Wayland on Intel Kabylake. Anyone else have any clue? :confused: Perhaps it's driver related?

**Comment by Binero** [comment] 2017-02-06 14:41
I'm running GNOME / Wayland on Intel as well.

**Comment by Xaeroxe** [comment] 2017-07-19 16:12
```
$ cd amethyst
$ rg unsafe
amethyst_assets\src\loader.rs
39:            unsafe {
71:                unsafe {
103:unsafe impl<A, E> Send for AssetFutureCell<A, E> {}
104:unsafe impl<A, E> Sync for AssetFutureCell<A, E> {}

examples\04_pong\main.rs
62:unsafe impl Sync for PongSystem {}
```

Given that we don't use glutin in any unsafe ways this probably isn't our bug.  If @Binero can reproduce it still we'll need more information to identify what the exact cause is.  Until more information is available I'm going to close this.

**Closed by Xaeroxe** 2017-07-19 16:12 UTC
Labels: diff: easy, pri: important, type: bug
