### ISSUE TITLE
Text editing delay bypass bug

### ISSUE THREAD

**Issue by jojolepro** [amethyst/amethyst#711] opened 2018-05-11 13:26 UTC
When using the text edit feature in 
cargo run --example ui
if you set your cursor between two letters and press a key, the typing delay will not be taken into account and the text will appear super fast.

**Comment by Xaeroxe** [comment] 2018-05-14 15:10
Can you clarify what you mean by "typing delay"?  I'm not familiar with such a concept.

**Comment by jojolepro** [comment] 2018-05-14 18:06
The delay between 2 letters being added to the text while holding a key down.

s -initial delay- ssssssssss-typing delay-sssssssssssssssss

When pressing a key while being between 2 letters it bypasses both delays and fills instantly the maximum allowed space.

**Comment by Xaeroxe** [comment] 2018-06-05 14:33
UI example behaves identically to other text editors on my system (Windows 10).  What platform are you using @jojolepro ?

**Comment by Xaeroxe** [comment] 2018-06-15 23:36
Closing, cannot reproduce.

**Closed by Xaeroxe** 2018-06-15 23:36 UTC
Labels: pri: normal, project: ui, type: bug

**Comment by jojolepro** [comment] 2018-06-20 20:09
Bug occured on arch linux. I'll try to reproduce if I don't forget...

**Comment by jojolepro** [comment] 2018-06-21 20:42
Can't reproduce :+1:
