### ISSUE TITLE
Communication & Documentation Strategy

### ISSUE THREAD

**Issue by oraknabo** [amethyst/amethyst#500] opened 2017-11-29 16:59 UTC
I'd like to propose the creation of a strategy for dealing with the website, wiki, API documentation, book, and any other non-code materials related to Amethyst. The goal of this issue is to start a discussion to work out the details of the strategy itself. Once everything is resolved, these details could be documented on the wiki for future reference. 

# Current Issues
While there have been some great efforts made to communicate the basic concepts behind the project and provide educational materials, it can be difficult to know what is relevant to the current codebase. It also seems like many important details are spread out in a lot of different places. While I don't propose taking away any of the current systems where these items reside, I would like to discuss ways of focusing each one on specific audiences and reorganizing some of the content to make it easier to digest. 

I've done a lot of reading in the website, book, wiki, issues, code, examples and current pull requests but I still don't know if I have a full understanding of the project. My main goal is to lower the barriers to entry for other people (like myself) trying to find a way into learning about this project and contributing to it.

# Benefits
I don't know what final form this strategy would take. It could end up including anything from style guides for documentation to procedures and templates for adding information to the wiki and website. Whatever the form, the goal would be to reduce random/spontaneous contributions that lead to confusing and unpredictable documentation and conflicting information.

I also think that if an organizational system like this is designed properly and communicated clearly it can also help reduce the challenges of keeping everything up to date while making it easier for contributors to know where to update the docs when significant changes are made to the source code.

# From Strategy to Action
If this goes forward and everyone reaches a consensus,  I (and anyone else) could then submit new project:docs issues to bring the existing materials in line with the new guidelines and identify new materials that need to be written. I don't want to flood the issue tracker with too many new items, so hopefully working out the strategy first will help reveal the highest priority items. 

While I don't mind doing the majority of the work on this, it goes without saying that if anyone wants to claim any specific task that would certainly be welcome.

Before I can get started on any of this, I need to identify and document what people are happy with and what they think needs reworking.  This is probably going to take a decent amount of time and communication, but it's important for me to approach this in a way that includes everyone's input. I understand that other people are busy and I don't want to distract them from the progress they're making on actual systems, but I will probably need to ask a lot of questions in the chat. 

# Is it Even Necessary?
Please let me know how much something like this is needed (or even wanted) by the current contributors. At some point, trying to organize the documentation of a system this way becomes a kind of project management task and I want to make sure I am not seen as trying to steer the course of development in any way that's unwanted.

I'm aware of the brief guidelines on [writing documentation](https://github.com/amethyst/amethyst/blob/develop/CONTRIBUTING.md#writing-documentation) covering the book and API and that the [website has an issue tracker](https://github.com/amethyst/website/issues). I've also seen that progress is being made on the book to keep it in line with new systems. I don't want to criticize those efforts but I think it could benefit the project to have a higher-level discussion about separation of concerns and audience consideration in relation to these materials.

**Comment by torkleyy** [comment] 2017-11-29 18:33
> At some point, trying to organize the documentation of a system this way becomes a kind of project management task and I want to make sure I am not seen as trying to steer the course of development in any way that's unwanted.

That you influence the project to some degree is wanted! After all, this is a community project and by its very nature every contributor influences its future and development.

**Comment by oraknabo** [comment] 2017-11-29 22:26
@torkleyy - I just don't want to show up out of nowhere presuming to know the best route for development when other people are contributing actual, working systems.

# Materials/Venues
I'm not sure what the best name for this is, but this is everything I could find that represents the project to an audience outside of the realm of source code:

 - Website/Blog (Marketing/Updates/Links to other stuff)
		https://www.amethyst.rs/
		https://www.amethyst.rs/posts/
 - API Docs (code generated)
		https://www.amethyst.rs/doc/master/doc/amethyst
 - Examples
		https://github.com/amethyst/amethyst/tree/develop/examples
 - Book
		https://www.amethyst.rs/book/master/html/index.html
		https://github.com/amethyst/amethyst/tree/develop/book
 - Wiki
		https://github.com/amethyst/amethyst/wiki
 - Issues Tracker
		[RFCs](https://github.com/amethyst/amethyst/issues?q=is%3Aissue+is%3Aopen+label%3A%22type%3A+RFC%22)
 - Chat
		https://gitter.im/amethyst/home

I have some comments I'm putting together about each of these but just listing them out is enough to start with. Please let me know if I've missed anything.

# External Systems
These, I'm assuming, will have their own books, docs wikis & trackers that will be separate from the Amethyst strategy but need to be linked in any appropriate places from this end:
- Specs
https://github.com/slide-rs/specs
- Citrine
https://github.com/amethyst/citrine
- Tools
https://github.com/amethyst/tools

# Audience
The way I see it, there are four distinct audiences served by the materials listed above:
1. - **The General Public** 
 _anybody, people researching interesting Rust projects but not making games, people wanting to make games but not sure which engine to use..._
 mostly served by the website
1. - **GUI/Tools-Focused Developers** 
_people wanting to make games who would wait for tools to be stable before trying_
served by a different book managed under tools repo?
1. - **Code-Focused Developers**
_people who want to jump in and make games with or without GUI-based tooling_
served by wiki, book, website, examples
1. - **Contributing Developers**
_anyone working on the engine itself_
served by wiki, tracker, chat

This is probably a big oversimplification. I'm sure there will be a big grey area between 2 & 3.
Again, I will have more to say about these in future comments.

# Questions
 - Are any of the Venues failing to serve any of the Audiences in ways that can be addressed immediately?
 - What are the biggest pain points in managing the Venues in the face of changing source code? 
the wiki, book and examples seem to be the most fragile. I have some ideas about how to address this but I want to write up some ideas in more detail. API Docs should be fine as long as documentation comments are maintained in code and code reviews take them into account.

I'll stop there for now until I've put more of my thoughts down and gotten more feedback on my previous comments.

**Comment by oraknabo** [comment] 2017-12-01 23:44
# Scope & Structure
I've already touched on the subject of scope briefly by mentioning external sites, but I also want to work toward defining the scope of each Venue I mentioned above.

In terms of overall scope, it can be helpful to see the Venues as individual nodes in a larger tree structure. The website would be the root node and would be the best entry point to direct visitors to other resources from. Users could enter from any point in the tree, (like the github repo or chat) but it's important to help them understand where they are in the tree and how to navigate to other parts.

With this model in mind, we can start to identify items that may be out of place (or even unreachable from the tree) and what might be missing in any given Venue. It can also help ensure that new information goes to the most appropriate place while, at the same time, reducing overlap.

Below the website, each Venue should primarily be targeted at only one or two Audiences with immediate links other Audiences can follow to material better suited to them.

# Venue-Specific notes
This started out as some loosely organized notes, but it seems to be moving in the direction of becoming a first draft. I welcome any comments, criticisms or changes to anything below: 

- **Website**
The main responsibility of the website is to direct each Audience to the materials (Venue) that will best serve their needs.
  - For the general public that means describing the project as clearly as possible so they can decide whether they want to know more or are even in the right place.
  - For what I call "GUI-focused" devs, it would be linking them to the book, docs and git repo for the tools to learn to install & get started using tools. 
  - Other devs will probably want to see the book and API docs and the book could direct them to the git repo and samples
  - Potential contributors should probably be sent straight to the wiki where they can see guidelines on how to create issues, read the contributor guidelines and documentation strategy, and follow a link to the chat

   I think it's useful to list the system updates on the site (which could eventually expand to a full blog), it could probably benefit from a discussion about which audiences it's currently serving.  

- **API Docs & Source Comments:**
Don't use comments to explain what the code is doing. Focus your energy on making the source code as readable as possible. Instead, use the comments to explain why the code is the way it is. Imagine you're walking one of the Audience members through your work. Try to envision anything you would need to explain for them to understand then, succinctly, put that in the comments. If possible, try this with a real person or even a [rubber duck](https://rubberduckdebugging.com/). 
When you're the only person who knows why something was done the way it was, you're keeping valuable information outside of the documentation scope. You become a dependency to the user's understanding. Finding out where that information fits in the documentation and putting it down decouples you from the code. Also making an unconventional solution understood protects it from being scrapped in future updates by others who can't figure out why it's even there.

- **READMEs**
This should follow the same rules as the inline comments but at a systems level. If there's something unconventional or no-obvious about a system or you need to explain why some module is in one place instead of somewhere else, it probably goes in a readme file.
Readmes should also contain links to anything relevant in the API Docs and Wiki do try to minimize duplicating information.

- **Chat & External answers**
While it's good to have a chatroom where people can ask questions, it poses a couple of problems to documentation. Chat is ephemeral and documentation needs to be predictable and easily discovered. While I wanted to include chat here as part of the strategy, I see it existing on the farthest edges of the documentation scope. With that said, it can be useful to direct users answers they need in the docs.
If you ever find yourself answering a question in chat or email, on an external site like StackOverflow or even in a face-to-face conversation that isn't covered anywhere else in the docs, think about whether it also belongs somewhere else in the tree. In some cases you may even want to put it the docs first and then answer the original question by linking to it.

- **Book/Examples**
 The book is probably going to be the most fragile part of the whole strategy, but it should be possible to write it in a way that only needs to be updated when there are breaking changes to the API. One possibility is to create a suite of tests around the examples and book content that could be run to determine where changes need to be made in these areas.

- **Wiki**
The wiki becomes a sort of catch-all for anything that doesn't fit anywhere else, but in relation to what I've mentioned about Audience and Scope, I think it should serve two main purposes
  - For Devs:
    - Getting Started (links to book, examples, main readme on repo)
    - Examples & Tutorials that don't belong in the book
    - Best Practices
    - Faqs?
    - Available options for ron files
    
  - For Contributors & anyone interested in diving deep:
    - Project Vision & History
    - Development Roadmap
    - Systems details and Diagrams that don't belong in READMEs
    - Documentation Strategy
    - Future plans & Acceptance Requirements for new systems
 
   Some things that end up in the wiki could probably find a home in the website, book or READMEs. I'm not saying there shouldn't be a wiki, but there should be a serious discussion about its place in the scope and whether any items there belong in a better, more easily discovered place.  
# General Guidelines on Style
Try not to be boring, but also don't try too hard to be funny. IMO, there's nothing worse than docs full of memes and [inside jokes](https://docs.python.org/3/library/pprint.html).

For the sake of ESL readers, it's probably best to avoid colloquialisms.

Be clear and concise. The main value of good documentation to an end user is that it solves their problem.  

Try to avoid saying anything is "easy", "trivial" or "obvious". Users are probably reading the docs because it's not as easy or obvious as you think.

If you can describe something better using diagrams, charts, tables or lists, do it. If you think a diagram would be useful but don't have the skill or tools to make one, start an issue so someone else can help you.

If you use an acronym or refer to a high-level concept, always explain them briefly or provide links that clarify them for the reader.

# A Final Note

If people don’t know why Amethyst exists or why they would want to use it over other engines, they won’t use it.

If people can’t figure out how to install, they won’t use it.

If people have to reverse-engineer the code to get started, they won’t use it.

A well focused website, book, readme files and comprehensive API coverage can solve the majority of these problems.

No matter how good your code is, how efficient & clean you make it, no matter how much time you spend making it idiomatic and boilerplate-free, if it's not documented, it will be basically invisible to 99% of potential users.

Good documentation can be one of your best sales tools in trying to convince developers to use the code it represents. If your documentation is clear, organized and helpful it can go a long way to convincing potential users that your systems are well engineered.

**Comment by torkleyy** [comment] 2017-12-02 05:02
Wow, thank you, these are definitely many interesting points. I don't think that we should split the book into GUI and non-GUI, it's probably better to explain that in one book, at least for now. I wonder what @Aceeri @Xaeroxe @Rhuagh @omni-viral think about this, but I like your other proposals :+1:

**Comment by Xaeroxe** [comment] 2017-12-02 07:32
Documenting GUI stuff is going to be way easier to talk about when we have a GUI to document.  Otherwise I generally like these guidelines.  I think a condensed version of these might even be valuable to have in contributing.md.  my only criticism of the content thus far is that it seems to have been written with the assumption we don't find documentation to be valuable.  I don't believe anyone here would ever suggest documentation isn't valuable, it's mostly just a very unfortunate omission at this point.  We're only just starting to see the light at the end of the tunnel on our "work in progress" status.  To be clear Amethyst will likely always be a work in progress, but we're finally starting to reach the point where we have something useful to the general public.

**Comment by oraknabo** [comment] 2017-12-02 08:06
@Xaeroxe As I mentioned in the first post, I think there's a lot of great content already in the docs so I certainly don't think anyone here undervalues documentation. My primary goal with this strategy is to make it easier to discover. 
The appeals to the importance of documentation are mostly aimed at future contributors but this is a very rough draft and I'm happy to remove anything you think is unnecessary.

**Comment by oraknabo** [comment] 2017-12-02 16:00
@torkleyy - Separate manuals was just an assumption I started out with, mostly because I'd seen people discuss Specs having its own book Amethyst's docs would link out to and because the tools have a their own repo. I agree that it's probably best to consolidate these since, IMO, there are already enough different parts to all of this for it to easily become confusing.

**Comment by oraknabo** [comment] 2017-12-03 15:53
# Strategy Goals
- Make answers to user questions easily discovered
- Develop approaches that ensure docs keep up with code changes with minimal effort
- Reduce overlap, duplication and confliciting info
- Communicate the project's values to new contributors

**Comment by futurepaul** [comment] 2017-12-03 17:06
Right now my hope for keeping the book from breaking is to have an example per chapter. That way, if an example doesn't compile, it's clear that the corresponding book chapter needs to be fixed with the same changes needed fix the example. Not sure if this is sustainable or how far it can grow?

Overall it sounds great to have more strategy around documentation. There are a lot of "big" engines that have very poor docs, so it's obviously a difficult problem.

Since working on the book is scratching my own itch right now, here's how I usually approach tutorials as a user:

* Follow the early steps nearly verbatim, but maybe swap a few names of things to make sure I'm not just typing mindlessly.
* At around the midpoint of the tutorial, branch off and do my own thing, while revisiting the tutorial to explain further concepts.
* If the tutorial has put down a good foundation, and points to helpful resources, I can keep building my own thing. If I haven't actually learned anything but merely typed the code without understanding, I end up stuck.

So my goal in writing the tutorial is to provide the how, but with enough direction toward the "why" that someone can find the information they need.

In practice, the Specs book, some theoretical amount of Gfx documentation, and relatively complete API docs would be a good quantity of "why" to have, in my opinion.

I also think setting expectations for the level of ergonomics would also be helpful when presenting Amethyst to a new user. Obviously everything computable is possible, but what specific aspects of game dev does Amethyst make "easy" or "well-structured" right now, and what does it plan to address in the future? A "no bamboozle" policy, if you will.

**Comment by oraknabo** [comment] 2017-12-03 19:54
@futurepaul - Do you see the ergonomics statements fitting better into the book, the website or the "vision" articles in the wiki? While I'm sure every contributor has a slightly different view of this, I am also interested in their visions of the finished engine and the kinds of projects they'd like to see it enable.
Your plan with examples sounds good and probaly --- any need for the tests I mentioned. The only advantage I could see in using tests would be that failed assertion messages could refer directly to where the book needs fixing, but having an example tied to each chapter probably comes close to that anyway. 

# More on Wiki & READMEs
After further consideration, I wanted to spotlight a couple of overlap issues I see between the wiki and READMES:

The "Getting Started" wiki-page I mentioned is probably not even necessary. The main repo README is probably already the best place for that information with everything a dev needs to link and get started. Contributors can follow a link to CONTRIBUTING.md which could link to the docs strategy which might also belong in an .md file in the main repo.

It's probably worth considering the advantages to putting some things in the repo. Probably the biggest is the ability to keep things inline with the source control history and also make it easier for them to be edited and discussed by pull request the same way you guys are currently doing with the book. 

The main advantage of the wiki over the repo is the sidebar that makes finding your way to information easier. Maybe that could also link to all the .md files in the repos (or one wiki page could do that).

While I think the FAQs and non-book reference guides & tutorials probably still belong on the Wiki, anything essential to the code might be better to put in the repo for the case of devs who clone the repo and read the .md files, but never visits the wiki. CHANGELOG.md is a great example of this.

Another way to look at the README/Wiki split is to try to keep anything stable in the repo & book and put more speculative stuff in the wiki but if we went that route the ron file reference I mentioned would probably need to go int the book. 

If we don't want to overwhelm the repo with .md files, we could also make sure there are only the README, AUTHORS & License files in any single directory and put all of the rest in a documentation folder on the top level.

I don't really have a concrete recommendation here, but it would probably be a good idea to define clear definitions for what belongs in each place.

**Comment by Rhuagh** [comment] 2017-12-04 07:15
I think the vast majority of documentation should be in the repo. README + other .md, api docs and the book should cover most things imho.

**Comment by erlend-sh** [comment] 2017-12-04 10:49
In any case, the most important task is to write the content. As long as it’s all in markdown it will be easy to move things around later as needed.

**Comment by oraknabo** [comment] 2017-12-05 03:40
Sorry about adding even more to the load on here, but these keep getting out of hand. I went through everything in the repo & wiki in detail and came out with a new outline and a few notes:

### READMEs & Repo .md Files
- Repo Home/Getting Started (link to book, API Docs, chat) 
- Authors
- License/Copying
- Changelog
- Contributing/Documentation Guidelines (links to chat, wiki)
- Development Roadmap
- Systems details (in each folder, link to related RFCs?)
- Examples descriptions (link to book)

### Book
- Coding Tutorials (links to examples, API Docs)
- Tools overview & instructions (eventually)
- Reference Appendices (glossary, config file options, etc.)

### Wiki
- Project Vision & Influences
- Design Docs/Acceptance Requirements for proposed features

**What should happen to speculative materials on the wiki after systems are implemented?**
This [renderer](https://github.com/amethyst/amethyst/wiki/Renderer-Design) page is a good example. I'd probably move any relevant parts to the README for the amethyst_renderer package and then update with notes about future plans.

**The best time to update design docs** pages seems to be right after a related RFC is closed to summarize decisions made during discussion. Any discussion of what to do with specific design docs pages should probably go in its own future RFC issue. 

**The linked [Codenames](https://github.com/amethyst/amethyst/wiki/Codenames) page doesn't exist.**

The [Releases](https://github.com/amethyst/amethyst/wiki/Releases) & [Workflow](https://github.com/amethyst/amethyst/wiki/Development-Workflow) pages overlap somewhat with CONTRIBUTING.md but aren't linked from there (though Workflow does link to it). Not sure the wiki's the best place for these. **Maybe a "Contributing" folder in the repo** with CONTRIBUTING.md, the docs strategy & these two would be worth trying?

**Remove the [CLI](https://github.com/amethyst/amethyst/wiki/CLI-Tool-Design) page?** Anything relevant about ECS design should probably move to Specs but there should probably be a link to the Specs repo with some info about it on the main README.

**Is [Other Game Engines in Rust](https://github.com/amethyst/amethyst/wiki/Other-Game-Engines-in-Rust) a reference for possible contributors or it a community awareness thing?** If it's more for the public, maybe it belongs on the website. We could also just link to [arewegameyet?](http://arewegameyet.com/categories/engines.html) so we don't have to worry about keeping it up to date.

**Comment by torkleyy** [comment] 2017-12-09 21:50
Another thing I want to add here:

In order to keep the docs / other material up to date we could keep a `PULL_REQUEST_TEMPLATE.md` (I think GH can even recognize that) and place some todos in it which the PR author has to tick.

**Comment by torkleyy** [comment] 2017-12-09 22:02
> The best time to update design docs pages seems to be right after a related RFC is closed to summarize decisions made during discussion.

I'd say the design docs should be updated together with the implementation of the RFC. Otherwise we may end up writing a design which we abandon because the implementation ended up being different from the original RFC.

> I'd probably move any relevant parts to the README for the amethyst_renderer package and then update with notes about future plans.

Expanding the subcrates' READMEs sounds like a good idea.

> Is Other Game Engines in Rust a reference for possible contributors or it a community awareness thing?

I don't know, because I didn't write it. Maybe it could be rewritten to be more like a comparision?

---

I think you have a lot of good ideas here! If you want, you / other contributors can start creating PRs which

* add an overview (maybe in the README) which links to other docs / resources
* decide on either the "Workflow" wiki page or the CONTRIBUTING.md file and put the information there
* create a roadmap (maybe taking ideas from https://github.com/amethyst/amethyst/pull/163)
* create a pull request template

This way, we can implement bit by bit with PRs, check it follows these ideas/agree on something else and slowly migrate to a better docs & communication architecture.

**Comment by torkleyy** [comment] 2017-12-10 10:30
One thing @Xaeroxe and I (IIRC) agreed on before was that it might be good to have the book explain the basics, so that you get started, and that the more detailed stuff should go into dedicated books (so one book for the renderer, one for the recommended physics crate (rhusics), one for the state machine we provide (maybe `machina`), ..). Is this still something we want?

**Comment by oraknabo** [comment] 2017-12-11 00:54
@torkleyy I started pulling together various stuff from my notes here and paring it all down into a .md file that could go along with CONTRIBUTING.md. I'll probably get a chance to work it into a full PR sometime in the next week.

I think either multiple books or breaking the book up into distinct sections that basically work on their own could be good. Splitting them off depends on how much each section would need to refer back to the basic "getting started" material. I could see it being structured like a car repair manual with a first section on overall maintenance & tune up and then detailed sections on the engine,  brake system, electrical, etc.

**Comment by zacnomore** [comment] 2018-01-11 05:13
The FAQ in the repo hasn't been a huge topic in this discussion but I think it's worth including. Currently it has only one question. Some ones possibly worth answering:
What is this?
Where did the name come from?
Why would I use it?
How can I contribute?

It will probably have some duplication of other info elsewhere but I often look to the FAQ for broad strokes like that.

**Comment by oraknabo** [comment] 2018-01-13 17:24
@zacnomore I agree that there should be a FAQ and it should have more info. The easiest way to avoid duplication is linking to the appropriate docs in the repo & faq whenever possible. THose links would still need to be updated when big changes are made elsewhere, but it would be less work than updating paragraphs.

Do you think it goes well in the Wiki? I'm mostly proposing to divide the materials for contributors from the ones for developers but this one would probably cover both. It might go better in the repo so people that fork or clone the source have quick access to it but think as long as we put a link to it in the main repo README, it would also be fine to leave it in the wiki.

**Comment by zacnomore** [comment] 2018-01-13 18:36
@oraknabo To my eyes, this project has been architected to allow developers to dig into the engine to make it suit their project. It's modular so they can swap out pieces as they like as well. I think the closest comparison would be the [atom flight manual ](https://flight-manual.atom.io/). The first half is basic usage but the second half is how to make it your own with packages and configuration.

So, why the division between the developers and contributers in the docs?

**Comment by oraknabo** [comment] 2018-01-13 19:19
@zacnomore The main goal of this strategy is having a logical place for everything that's both easy for
- users to find answers to their questions without having to look in multiple places
- contributors to know where to put new docs and what needs changing when code is updated

I tried to define 4 main audiences and understand where they would be looking first out of the many places we have to put info. What I basically settled on so far is:

- stable materials for developers/general users will mostly go in the book and API docs
- anything stable for contributors goes in the repo under a Contributing directory
- the main repo README will direct users to the items above and give any other necessary quick-start info
- the wiki will be reserved for more speculative stuff like specs describing proposed features

In this scheme, the FAQ probably goes in the main repo next to the README.
If you have any ideas about this, I'm happy to hear them.

**Comment by torkleyy** [comment] 2018-04-08 16:48
@oraknabo Are you still interested in working on this? Otherwise I recommend we postpone this to 1.0.

cc @amethyst/engine-devs

**Comment by jojolepro** [comment] 2018-04-11 23:56
1.0 is a long long way ahead. Docs aren't in a really bad state, so this can wait little bit. We often see new devs coming by, but the issue is that they don't stick around much. I think its mostly due to the long response time to their questions ansd open issues. Maybe we should centralise the fast communication routes a bit more and be more alert for questions. (I dont think we should have both discord and gitter at once, personally, I answer faster on discord because its always opened)

**Comment by OvermindDL1** [comment] 2018-04-12 15:10
And discord actually has dark themes...  (does gitter have any kind of themeing yet?)

Plus IRC<->Discord bots are a dime a dozen (even I make/run one for a game-specific purpose), most programmers I know live on IRC (myself included).  :-)

**Comment by Xaeroxe** [comment] 2018-04-12 15:17
@OvermindDL1 I can't believe I didn't think of this the first time you mentioned you didn't like gitter because you didn't like electron apps.  Gitter has an IRC bridge https://irc.gitter.im/

**Comment by OvermindDL1** [comment] 2018-04-12 15:46
Lol, hmm, I wonder how you join specific rooms...

**Comment by jojolepro** [comment] 2018-08-13 19:44
We now have an improved book, multiple PR fixing issues with the book and a growing following after the recent 0.8 release and mass advertising campaign we did. Keeping the book up to date when creating new features or modifying them is now mandatory as written in CONTRIBUTING.md.

There seem to be a lot of information here, but should we close this issue or let it stay open forever?

**Comment by fhaynes** [comment] 2018-11-28 19:15
The new Documentation Team will find this very useful, let's leave it open for now.

**Comment by fhaynes** [comment] 2018-12-23 23:50
Closing this as the docs team can now organize [here](https://openproject.amethyst-engine.org/projects/documentation/work_packages)

**Closed by fhaynes** 2018-12-23 23:50 UTC
Labels: diff: hard, project: docs, status: stalled, type: RFC, type: task

**Comment by zacnomore** [comment] 2019-10-25 21:10
@fhaynes That link is broken now, where should we look now?

**Comment by distransient** [comment] 2019-10-26 02:20
Current discussion is distributed between the forum and discord
