### ISSUE TITLE
[BUG] Could not compile `metal`

### ISSUE THREAD

**Issue by gaviriacc26** [amethyst/amethyst#2018] opened 2019-10-25 18:26 UTC
## Description

I recently started a new project with the amethyst tool and tried to build it with cargo, but it is breaking when trying to compile metal v0.15.0 as you can see in the image below.

## Screenshots and Logs

<img width="1151" alt="Screen Shot 2019-10-25 at 13 20 59" src="https://user-images.githubusercontent.com/55761757/67594887-eee23500-f72a-11e9-8cad-5610a92e378c.png">

## Environment

2. MacOS Catalina 10.15
3. Amethyst 0.13.2

**Comment by distransient** [comment] 2019-10-25 19:44
Dupe of https://github.com/amethyst/amethyst/issues/2011

**Closed by distransient** 2019-10-25 19:44 UTC
Labels: status: needs triage, type: bug
