### ISSUE TITLE
[BUG] Text not apering in release builds. and random aperance in debug builds

### ISSUE THREAD

**Issue by mralve** [amethyst/amethyst#1655] opened 2019-05-27 18:43 UTC
## Description
Currently, when I add text it initially appears like normal in debug mode, but when running in a release it's completely gone, I've tried with multiple text fields and it still persists.

## Reproduction Steps

Add text to the screen and run in a release.

I am currently reproducing this here.
https://github.com/mralve/Zombie-Curtains-3/blob/bcedf0088355bad2a53f46e615c93d44b375d8f6/src/zombie_curtains.rs#L121

## What You Expected to Happen

Normal text rendering.

## What Actually Happened

No text appears at all.

## Screenshots and Logs

If applicable, add screenshots to help explain your problem. Any relevant logs would be helpful as well.

## Your Environment

Linux Arch.
XFCE 4.
 1dd1417

**Comment by jojolepro** [comment] 2019-05-27 22:39
Cannot reproduce with the ui example.

**Comment by mralve** [comment] 2019-06-06 18:35
This seems to be have resolved my combining DrawFlat2DTransparentDesc, DrawFlat2DDesc, DrawUiDesc in one subpass in render_graph.

**Comment by mralve** [comment] 2019-06-07 16:48
I managed to reproduce this issue again

**Comment by Frizi** [comment] 2019-06-11 16:12
I think this is connected with `#1686` which gives a few more examples. I will close this in favour of the other issue and track that there.

**Closed by Frizi** 2019-06-11 16:12 UTC
Labels: status: needs triage, team: ui, type: bug
