### ISSUE TITLE
Re-export specs-derive

### ISSUE THREAD

**Issue by PvdBerg1998** [amethyst/amethyst#551] opened 2018-01-30 19:07 UTC
By re-exporting `specs-derive` one would be able to use the macro's very easily. I tried manually adding the dependency, but it requires `extern crate specs`, and I don't want to accidentally compile a different version of `specs` next to the already exported `ecs`.

**Comment by torkleyy** [comment] 2018-01-31 17:40
I don't think we can easily reexport `specs-derive`, because it will still require a global `specs` item.

**Comment by torkleyy** [comment] 2018-01-31 17:41
This is a very annoying problem with procedural macros :(

**Comment by Rhuagh** [comment] 2018-01-31 17:42
I think we can do macro_use on the specs reexport and enable the derive feature, if a user do macro_use on amethyst they get it then also

**Comment by Aceeri** [comment] 2018-01-31 22:00
Might want to look at what serde does for proc macro re-exporting. (I know they did it somehow I just can't remember what)

**Comment by randomPoison** [comment] 2018-07-17 03:38
I've been looking into this a bit, since I very much would like to be able to derive `Component` and `SystemData` without having to manually depend on shred, shred-derive, specs, and specs-derive. Re-exporting a procedural macro in Amethyst is totally possible, and quite easy to do: [Simply slap `#[macro_use]` on your `extern crate` statement](https://github.com/serde-rs/serde/blob/4e54aaf7963c3580cc50b56842949b0ce6b3a997/serde/src/lib.rs#L297) and you're good to go.

The hard part is the way the generated code references traits and other types. For procedural macros, it's generally considered best practice for the generated code to reference the appropriate traits/types by absolute path, that way the code using the derive doesn't need those items to already be in scope. For example, the code generated by `#[derive(SystemData)]` would generally look like this:

```
#[derive(SystemData)]
struct MyData {}

// Generates:
impl ::shred::SystemData for MyData {
    // ...
}
```

[Relevant source code in shred-derive](https://github.com/slide-rs/shred/blob/f1437a7edb5861b173ef088110eda7a75a1a6e69/shred-derive/src/lib.rs#L48).

While this setup works perfectly for any code that depends on shred directly, it makes it hard for Amethyst to re-export the procedural macro because the client code no longer has a `shred` item at the root level, which means the absolute path no longer works. Specifically, the client gets a confusing error on `#[derive(SystemData)]` saying "No item `shred` found, did you mean `amethyst::core::shred`?".

---

I can think of a handful of solutions to this:

* Have Amethyst export something like a `derive_prelude`, which puts items for `shred` and `specs` at the root level again. Client code would do something like `pub use amethyst::derive_prelude::*;` in their `main.rs`, which would effectively restore the paths that the code generated by the procedural macros depends on.
* Duplicate the procedural macros for `Component` and `SystemData` in Amethyst, using the paths that are correct for Amethyst.
* Setup features for specs-derive and shred-derive that allow them to be configured to generate code that uses paths specific to Amethyst.
* Change specs-derive and shred-derive to not use absolute paths. This would require users to bring `Component`/`DenseVecStorage` or `SystemData` into scope when using the derive logic, but wouldn't require the libraries to be changed when used with Amethyst versus being used on their own.

Personally I think creating a new amethyst-derive crate and re-exporting and creating new Amethyst-specific derives is the simplest way to go, even if it results in code duplication. I'd like to get started on testing that out, but if there are any objections to that approach please let me know.

**Comment by jojolepro** [comment] 2018-07-17 13:14
>Change specs-derive and shred-derive to not use absolute paths. This would require users to bring Component/DenseVecStorage or SystemData into scope when using the derive logic, but wouldn't require the libraries to be changed when used with Amethyst versus being used on their own.

This is what makes the most sense in my head. However, you are free to use the method that you think will be best (both in simplicity, and maintenance cost)

**Comment by randomPoison** [comment] 2018-07-17 13:55
In general I prefer whichever approach puts the least burden on the user, so my preferred approach is the one that doesn't require developers to add a bunch of extra `using` statements when using the derives.

That beings said, I wouldn't be the only person maintaining the duplicate derives for amethyst, so if that extra maintenance burden isn't something the Amethyst dev team wants to take on, then I think having the generated code not use absolute paths is the next easiest approach to implement.

**Comment by jojolepro** [comment] 2018-07-17 14:07
@Xaeroxe opinion?

**Comment by Xaeroxe** [comment] 2018-07-17 14:32
Rust 2018 is going to make this a lot easier, so let's postpone this until we've completed a migration to Rust 2018.  Rust 2018 has a much simpler picture in regards to macro exporting.

**Comment by randomPoison** [comment] 2018-07-17 15:43
Is Rust 2018 adding any features to help with name resolution in procedural macros? The primary issue here isn't re-exporting the macros, that part is fairly trivial. The trouble is name resolution since the absolute paths to the items referenced by the generated code is different for Amethyst vs using specs/shred directly. If Rust 2018 is going to make that part easier, then I'm happy to postpone and avoid a bunch of unnecessary work (even if it means more boilerplate in the meantime) 🙂

**Comment by omni-viral** [comment] 2018-07-17 18:14
Serde do this by including `extern serde` into generated code BTW.

**Comment by jojolepro** [comment] 2018-07-17 18:50
@omni-viral I saw your new renderer you are making. If we can help let us know.

**Comment by randomPoison** [comment] 2018-07-17 19:24
@omni-viral That's pretty cool! It doesn't entirely help here, though, because the user would still need to list shred/specs in their `Cargo.toml`, which isn't desirable, IMO. An amethyst-derive crate could use that trick, though 😃

**Comment by omni-viral** [comment] 2018-07-20 08:52
@jojolepro offtopic.
BTW currently it's ash experiment. I'm not yet sure which path to choose: hal or ash.

@randomPoison What if `shred` will expose function for deriving `Component` and `amethyst` will reuse it and substitute `shred::Component` with `amethyst::ecs::Component`.

**Comment by torkleyy** [comment] 2018-09-07 14:38
Not sure if we can make this work. Something's telling me we can't just append an identifier to build the constant's ident.

**Comment by torkleyy** [comment] 2018-09-07 14:39
I think I tried it before and it didn't work, but maybe this is a recent change in some of the parsing logic.

**Comment by fhaynes** [comment] 2019-01-08 02:19
@torkleyy should this stay open?

**Comment by khionu** [comment] 2019-02-14 11:17
This should be tested again, since we're on 2018.

**Comment by torkleyy** [comment] 2019-02-14 12:15
@Xaeroxe Can you explain how Rust 2018 makes this easier?

**Comment by khionu** [comment] 2019-02-14 12:43
https://rust-lang-nursery.github.io/edition-guide/rust-2018/macros/macro-changes.html

**Comment by torkleyy** [comment] 2019-02-14 12:48
Yeah, I know about the changes, but none of them help the problem we're having here as far as I can see. Even if we can reference `specs` in the macro, you'd still have to include it in your `Cargo.toml`.

**Comment by khionu** [comment] 2019-02-14 12:53
Why? The proc macro should use its own dependencies, not the dependencies of the crate invoking it.

**Comment by torkleyy** [comment] 2019-02-14 12:58
Yes, definitely. The goal of this issue however is to invoke the procedural macro without adding dependencies to your project.

**Comment by khionu** [comment] 2019-02-14 13:02
If specs-derive is already being used by Amethyst, re-exporting it won't add anything.

**Comment by torkleyy** [comment] 2019-02-14 13:03
It doesn't add anything to Amethyst. The problem is the user has to add it to their `Cargo.toml` because the macro expects that it can import the `specs` crate.

**Comment by torkleyy** [comment] 2019-02-14 13:05
That's why Rust 2018 doesn't improve this - the only solutions that remain are:

* force the user to import items used by the macro
* rewrite the macro in Amethyst, exposing parts of it from some Specs helper crate

**Comment by khionu** [comment] 2019-02-14 13:26
> because the macro expects that it can import the `specs` crate.

Why can't it? If it's using the same `specs` version as Amethyst, which can be controlled through CI checking the dependency tree for more than a single version of `specs` (and we can do the same for other crates as well), then it should be able to use that.

**Comment by torkleyy** [comment] 2019-02-14 13:30
It cannot, unfortunately. Code will be generated at the user side. So that code needs to be able to import using a specific path (e.g. `use specs::Component`). However, that path can only be used if `specs` is a dependency in the `Cargo.toml`. And that means the user needs to specify the `specs` dependeny in their manifest.

**Comment by khionu** [comment] 2019-02-14 13:48
Ohh, I see the issue. The path generated by the macro... Well, that could be fixed via a configuration, couldn't it? `override_crate_import: Option<String>`

**Comment by torkleyy** [comment] 2019-02-14 13:54
Where do you want to pass that? The only option would be an attribute:

```rust
#[derive(Component)]
#[component(override_crate_import = "amethyst::ecs")]
pub struct MyComp;
```

And at that point, I don't think it's any better than

```rust
use amethyst::ecs::Component;

#[derive(Component)]
pub struct MyComp;
```

**Comment by khionu** [comment] 2019-02-14 13:55
Well, imo, the second option is fine.

**Comment by torkleyy** [comment] 2019-02-14 13:56
If we can all agree with that, great :)

**Comment by khionu** [comment] 2019-02-14 13:58
Actually, I think it's much better, because as is, it's technically an assumption of origin. Requiring they define the imports manually is an absolutely tiny thing.

**Comment by randomPoison** [comment] 2019-02-14 14:00
That second option is more inline with the convention for custom derives in the 2018 edition as well. It may not be sufficient on its own, though, since the generated code may reference other symbols (e.g. `Component` needs to specify the component storage).

**Comment by Frizi** [comment] 2019-03-10 13:15
Relevant serde PR which is solving similar issues https://github.com/serde-rs/serde/issues/1487
Note that amethyst could wrap the specs derives and override the crate in the same way.

**Comment by fhaynes** [comment] 2019-03-22 05:08
Closing this due to age and lack of progress. However, since there was some relatively recent discussion, if you'd like to work on it, please feel free re-open it.

**Closed by fhaynes** 2019-03-22 05:08 UTC
Labels: diff: easy, pri: normal, status: discussing, team: ecs, type: improvement
