### ISSUE TITLE
Can't enable profiler feature from external crate

### ISSUE THREAD

**Issue by JadeSnail** [amethyst/amethyst#657] opened 2018-04-21 07:00 UTC
I'd like to have a feature on my crate to enable the amethyst profiler, but the following Cargo.toml fails, with ```the package `Test` depends on `amethyst`, with features: `amethyst_animation` but `amethyst` does not have these features.```

```
[package]
name = "Test"
version = "0.1.0"

[features]
#profiler = ["amethyst/profiler", "amethyst_animation/profiler"]
profiler = ["amethyst/profiler"]

[dependencies.amethyst]
#optional= true
git = "https://github.com/amethyst/amethyst"
branch = "develop"
#features = ["amethyst_animation"] 

#[dependencies.amethyst_animation]
#optional= true
#git = "https://github.com/amethyst/amethyst"
#branch = "develop"
```

The commented lines are the different things I've tried, which all fail.

**Comment by zoonage** [comment] 2018-04-21 10:46
Confirmed that it is only an issue with `amethyst_animation`, looking into this

**Comment by zoonage** [comment] 2018-04-21 10:58
OK, so this is because the amethyst_animation crate is not re-exported by amethyst, maybe the crate isn't ready yet, I'll check

**Comment by zoonage** [comment] 2018-04-21 11:58
#658 put in to fix this

**Comment by jojolepro** [comment] 2018-04-21 14:14
Closing since its fixed.

**Closed by jojolepro** 2018-04-21 14:14 UTC
