### ISSUE TITLE
Fix appveyor CI failure due to dxguid

### ISSUE THREAD

**Issue by nchashch** [amethyst/amethyst#242] opened 2017-06-08 17:50 UTC
Appveyor CI failed on beta and nightly when testing #152 because apveyor couldn't build `dxguid` crate, also it failed on nightly when testing 0.4.3 (see [appveyor log](https://ci.appveyor.com/project/amethyst/amethyst/build/1.0.335/job/j2j1oulfsvjll89v#L217)) for the same reason.

**Comment by torkleyy** [comment] 2017-06-08 18:05
Created issue https://github.com/retep998/winapi-rs/issues/458

**Comment by torkleyy** [comment] 2017-06-08 19:32
This is caused by a regression https://github.com/rust-lang/rust/issues/42544

**Comment by nchashch** [comment] 2017-06-19 16:51
Should be fixed by rust-lang/rust#42728. I think we would close this issue once appveyor CI builds don't fail anymore, which should happen after this change propagated to rust's stable, beta, and nightly channels.

**Comment by ebkalderon** [comment] 2017-07-01 21:30
Examining the recently merged #250, it appears that the AppVeyor builds no longer fail on nightly but still do on beta.

**Comment by torkleyy** [comment] 2017-07-12 16:17
Seems this is resolved now.

**Closed by torkleyy** 2017-07-12 16:17 UTC
Labels: diff: medium, pri: normal, type: bug
