### ISSUE TITLE
[BUG] Debug lines only appear with certain y values

### ISSUE THREAD

**Issue by Rhadow** [amethyst/amethyst#1455] opened 2019-03-07 23:39 UTC
## Description

When drawing debug line using `add_direction` or `add_line` under `DebugLinesComponent`, certain Y value of the starting point parameter will make the line not rendered on screen. 

## Reproduction Steps

Please see detail code in the following gist:
https://gist.github.com/Rhadow/693b0bd8fc782c64f9c72c21be365208

Modify the y value from 7.0 to any numbers in this sequence `2, 6, 10, 14, 18, 22, 26...` at line 44 of main.rs should make the debug line appear on the screen.

## What You Expected to Happen

Debug line should show up with any y values.

## What Actually Happened

Debug line only shows up when y value is set to 2, 6, 10, 14, 18, 22, 26....

## Your Environment

1. Operating System: Windows
2. Operating System Version: Windows 10
3. Version of Amethyst: 0.10.0

**Comment by azriel91** [comment] 2019-03-17 07:52
Looks like the debug lines doesn't work properly with `Orthographic` projection, and still uses perspective. The special values are probably when the rounding is *just right* such that the computer decides to render the lines.

The following has the origin at the bottom left, with world coordinates going from 0 to 800 left to right, and 0 to 600 bottom to top.

![debug_lines_ortho](https://user-images.githubusercontent.com/2993230/54487086-43504700-48f6-11e9-97dd-cf73fc4eb417.gif)

You can see that the closer the vertical / horizontal lines are to the left / bottom, they become thicker.
Without the `+ 2` to the y coordinate here, you can't actually see the horizontal lines, which is likely the same as the original issue.

https://github.com/azriel91/amethyst/blob/0147fc828099613bd3f4573d28b72befa5a32201/examples/debug_lines_ortho/main.rs#L59

**Comment by azriel91** [comment] 2019-03-20 22:02
Likely duplicate of https://github.com/amethyst/amethyst/issues/1455

**Comment by Frizi** [comment] 2019-06-12 17:34
This is likely fixed with new debug lines pass in amethyst_rendy. Need to port and test the reproduction.

**Comment by azriel91** [comment] 2019-06-13 04:35
Confirmed it's fixed by rendy 👌.
Example PR: https://github.com/amethyst/amethyst/pull/1703
Video: https://imgur.com/ampnCrw

**Closed** 2019-06-13 05:54 UTC
Labels: diff: normal, pri: low, status: ready, team: engine, team: rendering, type: bug
