### ISSUE TITLE
Change `amethyst_renderer` lighting to use nalgebra

### ISSUE THREAD

**Issue by zoonage** [amethyst/amethyst#796] opened 2018-06-17 21:29 UTC
The lighting in the renderer has multiple comments like `TODO: Replace with a cgmath type when gfx version > 0.16`. Now that we are using gfx 0.17 this should be swapped to use cgmath

Example lighting with these comments;

```
pub struct SpotLight {
...
    /// Location of the light source in three dimensional space.
    pub center: [f32; 3], //TODO: Replace with a cgmath type when gfx version > 0.16
...
    /// Direction that the light is pointing.
    pub direction: [f32; 3], //TODO: Replace with a cgmath type when gfx version > 0.16
...
}
```

**Comment by termhn** [comment] 2018-06-18 05:11
I don't think this is actually possible even though we're on 0.17, could be wrong tho

**Comment by Xaeroxe** [comment] 2018-06-18 14:22
At one point in time there was a feature called `cgmath_types` that would have enabled this.  However 0.17 removed this feature.  Our next best option is `mint` types.  I'm not completely sure those are a significant improvement over the current situation so I'll mark this as low priority.

**Comment by jojolepro** [comment] 2018-09-18 11:10
Yes, but just rename cgmath nalgebra and the issue is valid

**Comment by Plotnus** [comment] 2018-12-10 07:32
Does this still need someone to work on it?
 I see it doesn't have an assignee, and I'm considering taking a swing at it as a first contribution.

**Comment by termhn** [comment] 2018-12-10 07:41
@Plotnus Thanks for taking a look, but I believe this issue should actually be closed as the story will be different in a few weeks when `rendy`, amethyst's new renderer, gets introduced; and, there's not a simple way to solve it with nalgebra currently.

**Closed by termhn** 2018-12-10 07:41 UTC
Labels: diff: medium, good first issue, pri: low, project: rendering, status: ready, type: improvement

**Comment by termhn** [comment] 2018-12-10 07:46
@Plotnus Oh: If you'd like a good first project related to rendering then #1193 or #1151 might be good options; #1151 is also subject to change when `rendy` is introduced, however, but it still might be valuable in the interim and *should* be fairly easy to set up. Feel free to ask in #rendering channel on our Discord if you run into issues :D

**Comment by Plotnus** [comment] 2018-12-10 07:58
@termhn
Thanks for the info!
I'll take a look at 
[#1193](https://github.com/amethyst/amethyst/issues/1193). That looks like a good way to get my hands dirty with some rust game dev.

I'd say I'm more of a gameplay/engine type person. Gameplay, Gameplay Systems, AI, simple Physics stuff, things like that. Learning some rendering would be cool too ofc :)
