### ISSUE TITLE
[BUG] Brief Description Here

### ISSUE THREAD

**Issue by crimsonalucard** [amethyst/amethyst#2164] opened 2020-03-07 14:14 UTC
## Reproduction Steps

1. On a mac follow the pong tutorial until you hit the text "Now, try compiling the code."
2. Compile the code

## What You Expected to Happen

Code compiles and runs. 

## What Actually Happened

a dependency caused an error. err-derive

## Screenshots and Logs
```
error[E0433]: failed to resolve: could not find `__rt` in `quote`
   --> /Users/brianyeh/.cargo/registry/src/github.com-1ecc6299db9ec823/err-derive-0.1.6/src/lib.rs:145:63
    |
145 | fn display_body(s: &synstructure::Structure) -> Option<quote::__rt::TokenStream> {
    |                                                               ^^^^ could not find `__rt` in `quote`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0433`.
error: could not compile `err-derive`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

If applicable, add screenshots to help explain your problem. Any relevant logs would be helpful as well.

## Your Environment

1. OSX
2. Catalina
3. 
```
[package]
name = "pong"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies.amethyst]
version = "0.13"
features = ["metal"]
```

## Additional Context
None

**Comment by azriel91** [comment] 2020-03-08 00:07
heya, it's a duplicate of https://github.com/amethyst/amethyst/issues/2162. if you can update to `master`, you'll receive a fix. Otherwise gotta wait for a release (not sure how soon we'll do one, but shall ask the others)

**Closed** 2020-03-08 00:08 UTC
Labels: status: needs triage, type: bug
