### ISSUE TITLE
Modularization of Amethyst

### ISSUE THREAD

**Issue by lschmierer** [amethyst/amethyst#190] opened 2017-02-15 14:27 UTC
Tackling Issue #34 is long overdue in my opinion.
This issue is more or less the first step of **Part 1: Features** of the RFC #34.

Before adding more features (aka "shards") to the engine, current functionality should be modularized as much as possible.
Features can be enabled/disabled using *Cargos features*.

## Spotted Features (aka Shards)
Feature                                                    | depends on            | mandatory
------------------------------------------ | ------------------- | ------------
engine (core)                                            |                               |
config (project #152)                               | engine                    | yes
renderer (amethyst_renderer, gfx_device)  | engine, config  | no, enabled by default
transform system                                     | engine,             | no, enabled by default
asset manager                                          | engine                   | no, enabled by default

A little cleanup of the code base is probably required. See #191.

Feedback welcomed!

**Comment by ebkalderon** [comment] 2017-02-15 16:09
@lschmierer I believe you might have misunderstood the point of shards. `ecs` should not be considered a shard, it is a required feature of the engine. I have modified your table so it adheres more closely to the original shards concept:

Shard Name     | Depends on      | Crates needed                                     | Required? | Enabled by default?
---------------|-----------------|---------------------------------------------------|-----------|--------------------
engine         |                 | amethyst                                          | Yes       | Yes
assets         | engine          | amethyst                                          | No        | Yes
audio          | engine          | amethyst                                          | No        | Yes
physics        | engine          | amethyst                                          | No        | Yes
project (#152) | engine, assets  | amethyst, amethyst_project (?)                    | No        | Yes
rendering      | engine, project | amethyst, amethyst_project (?), amethyst_renderer | No        | Yes

Please note that shards are *not* equivalent to the engine's crate dependency graph! Please do not get them confused. Below is an incomplete crate dependency graph in table form for comparison:

Crate name        | Required dependencies | Optional dependencies
------------------|-----------------------|----------------------------------------
amethyst          | specs                 | amethyst_project (?), amethyst_renderer
amethyst_project  | yaml_rust             |
amethyst_renderer | gfx                   | gfx_device_dx11, gfx_device_gl, etc.

**Comment by lschmierer** [comment] 2017-02-15 16:14
@ebkalderon Thanks for the clarification, that shards are independent form the crate depndency graph was clear to me.

Your table looks pretty good. We should probably maintain it at some prominent place for reference.

**Comment by ebkalderon** [comment] 2017-02-15 16:42
Agreed, I'm on it! 👍 I'll put it up on the wiki right now.

**Comment by agmcleod** [comment] 2017-02-15 17:20
Question, are you looking at doing something similar to piston, where they are independent pieces? Or more of a better separation inside the main crate itself?

**Comment by ebkalderon** [comment] 2017-02-15 17:57
@agmcleod Good question! We definitely want to avoid the fragmentation endemic to Piston where the user has to assemble a bunch of disparate pieces together to make a game. We approach modularity from a different angle: Amethyst is presented to the user as a cohesive whole, but its parts can be used independently of the top-level `amethyst` crate if users desire more flexibility and prefer instead to "roll their own."

**Comment by lschmierer** [comment] 2017-02-15 17:59
Amethyst aims to be more a complete full feature game engine.
Features are far more coupled then it is the case in e.g. Piston.

In my opinion, only things that are useful without the full game engine need to be in separate crates.

**Comment by Aceeri** [comment] 2017-02-15 19:39
On a side note, I think it might be a great idea to have a section of the book that goes over what each module of the engine does along with all the systems added with amethyst. When I was trying to work with other engines my main annoyance was not really understanding the overview of what was going on with the individual systems of the engine (rendering, scene graph, physics, etc).

The project submodule will mainly be for convenience stuff, as in automatically adding configurations for systems to the ecs world at initialization, as well as updating them, etc.

**Comment by ebkalderon** [comment] 2017-02-15 20:58
**Posted by @ebkalderon on the amethyst/engine Gitter on [February 15, 2017 3:56 PM](https://gitter.im/amethyst/engine?at=58a4c07ade50490822d20b41):**

> Hey everyone! Everything from #190, #121, and #191 has been codified in the wiki under the new [Modularity Design](https://github.com/amethyst/amethyst/wiki/Modularity-Design) page. Check it out and feel free to discuss on Gitter. I'm dropping offline for a little while, so I apologies in advance if I don't get a chance to answer everyone's questions.

**Comment by msiglreith** [comment] 2017-02-16 17:37
Not sure if it totally fits here but I would propose that low level parts of the engine, mostly `resources`like graphics abstraction, audio abstraction, input manager, asset manager, etc, could live in separate crates as the inter-dependecies between those are usually quite low (in optimal case zero). These could be also picked up by other projects then.
All the processors/systems and components should be in one higher level crate due to huge dependencies between them. E.g If one wants to change the `Transform` part for a 2D game, it also requires further changes to the physics processors and audio processors, but this might be desirable for these type of games. On the other side you probably don't want to rewrite graphics backend and audio backend or collision detection parts as they are shared by pretty much all games.

**Comment by ebkalderon** [comment] 2017-02-16 19:21
@msiglreith This was the original reason for `amethyst_ecs` to exist, but people overwhelmingly voted to remove it. 😉

**Comment by Aceeri** [comment] 2017-02-16 20:34
Well imo `amethyst_ecs` wasn't so much a low level part of amethyst as it was just a wrapper over `specs`. So `specs` could just be considered the replacement for that crate (which just removes a layer of abstraction).

I think the main idea would be to separate a physics3d and a physics2d system into separate crates.

**Comment by ebkalderon** [comment] 2017-02-16 20:39
@Aceeri Sorry, perhaps I should have been more clear. I meant that I wanted `amethyst_ecs` to still exist to store the pre-built components, systems, resources, prefabs, etc.

**Comment by lschmierer** [comment] 2017-02-17 09:10
@msiglreith I like this approach.
@ebkalderon However, I quite don't understand what the `amethyst_ecs` would have to do with it.
When e.g. a transform system is exposed as seperate crate, it should probably store its components and systems within its own crate.
These seperate crates must not have an dependency on the the main `amethyst` crate.
But a transform crate would probably be dependent on `specs`.
The transform feature is just an example here, if this should be seperated from the core engine can be further discussed.
However, the arguments are valid for other possible features, too.
I think this is pretty much related to https://github.com/amethyst/amethyst/issues/191#issuecomment-280595134.

**Comment by Aceeri** [comment] 2017-10-20 06:08
Kind of outdated now, and somewhat a duplicate of https://github.com/amethyst/amethyst/issues/396.

**Closed by Aceeri** 2017-10-20 06:08 UTC
Labels: diff: hard, note: help wanted, pri: important, project: meta, type: improvement
