### ISSUE TITLE
Examples keep creating gfx buffers

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#1217] opened 2018-12-04 17:24 UTC
While an example is running, buffers keep getting created for no reason.

Log:

```
[INFO][gfx_device_gl::factory] 	Created buffer 19
[INFO][gfx_device_gl::factory] 	Created buffer 20
[INFO][gfx_device_gl::factory] 	Created buffer 21
[INFO][gfx_device_gl::factory] 	Created buffer 22
[INFO][gfx_device_gl::factory] 	Created buffer 23
[INFO][gfx_device_gl::factory] 	Created buffer 24
[INFO][gfx_device_gl::factory] 	Created buffer 25
[INFO][gfx_device_gl::factory] 	Created buffer 26
[INFO][gfx_device_gl::factory] 	Created buffer 27
[INFO][gfx_device_gl::factory] 	Created buffer 28

```

Examples where this can be observed:

* `renderable`
* `ui`

Examples where this cannot be observed:

* `sphere`
* `window`

**Comment by torkleyy** [comment] 2018-12-04 17:33
This issue existed for a long time (since at least 0.8) and was not fixed since then.

**Comment by msiglreith** [comment] 2018-12-06 21:57
FWIW: the sprite batching pass recreates and throws away vertex buffers intentionally. I'm not sure which other passes uses it so just to keep in mind. In OpenGL, it's not a bad thing to alloc&invalidate memory on the fly as the driver manages it for you, which also avoids additional synchronization, stalling the CPU. This could be prevented by manually ringbuffering but requires a more complex imlementation which didn't seem worth at the moment.

**Comment by aloucks** [comment] 2018-12-23 22:18
This also crops up in the Pong tutorial after adding the sprite sheet handle to `initialize_paddles` (before ever getting to the the text sections).

```
[INFO][gfx_device_gl::factory]  Created buffer 3
[INFO][gfx_device_gl::factory]  Created buffer 3
[INFO][gfx_device_gl::factory]  Created buffer 3
[INFO][gfx_device_gl::factory]  Created buffer 3
[INFO][gfx_device_gl::factory]  Created buffer 3
...
```

**Comment by aloucks** [comment] 2018-12-25 02:15
The continuous creation of buffers is chewing through quite a bit of CPU as well. I thought the high CPU was due to the rayon issue (#780 - which is also contributing here), but a pretty significant portion is in `glGenBuffers`. 

![image](https://user-images.githubusercontent.com/221559/50409464-dc246a00-07c0-11e9-8349-fe535de5172f.png)

![image](https://user-images.githubusercontent.com/221559/50409473-fa8a6580-07c0-11e9-9ebd-f88b55991593.png)

**Comment by atamis** [comment] 2019-02-05 00:20
Hey, I was running through the Amethyst Pong tutorial and ran into this bug. I got to
[part 2](http://localhost:3000/pong-tutorial/pong-tutorial-02.html), and got to the section after loading the sprite sheet and sprite sheet description, at which point, the game should show both paddles. However, it didn't, and instead started creating buffers left and right, several times a second. You can see the full logs
[in this gist](https://gist.github.com/atamis/02838411fd7df33890c30fb12fd65306), and I uploaded the project to [this repo](https://github.com/atamis/pong-buffer-bug/tree/master).

**Comment by miller-time** [comment] 2019-03-13 06:05
If anyone is interested in just silencing these messages in the logger, you can change the logger configuration like so:

```diff
-    amethyst::start_logger(Default::default());
+    amethyst::start_logger(LoggerConfig {
+        stdout: StdoutLog::Colored,
+        level_filter: LogLevelFilter::Warn,
+        log_file: None,
+        allow_env_override: true
+    });
```

Or by setting the env override:

```
AMETHYST_LOG_LEVEL_FILTER=WARN cargo run
```

**Comment by golergka** [comment] 2019-03-17 13:05
Any update on this issue? This line spams every frame and makes debug logging unusable (with Pong tutorial, at least):

```
[INFO][gfx_device_gl::factory]  Created buffer 3
```

If this buffer creation is not a bug, may be we can disable it from writing the INFO message every frame?

**Comment by vessd** [comment] 2019-03-17 13:37
@golergka the message is disabled on the master branch: https://github.com/amethyst/amethyst/pull/1404
For `v0.10`, you can use the solution above to disable messages in local project.

**Comment by fhaynes** [comment] 2019-03-23 07:41
Closing as this was resolved.

**Closed by fhaynes** 2019-03-23 07:41 UTC
Labels: status: discussing, team: rendering, type: bug
