### ISSUE TITLE
Resize is not working correctly

### ISSUE THREAD

**Issue by Rhuagh** [amethyst/amethyst#649] opened 2018-04-16 20:24 UTC
Resizing (atleast on my Mac) does not resize the framebuffers correctly. Increasing the size of the window cause black bars on the right and bottom sides. Decreasing the size cause the window to show an "odd" part of the original window.

<img width="1238" alt="screen shot 2018-04-16 at 22 23 30" src="https://user-images.githubusercontent.com/1011884/38833107-e616f36a-41c4-11e8-92d3-ec0ee5539e6c.png">
<img width="816" alt="screen shot 2018-04-16 at 22 23 59" src="https://user-images.githubusercontent.com/1011884/38833111-e88e319e-41c4-11e8-8a5b-3d0947efee44.png">

It seems as though the original window gets displaced down to the right when I decrease the size.

**Comment by jojolepro** [comment] 2018-04-16 20:26
Duplicate of https://github.com/amethyst/amethyst/issues/547 maybe?

**Comment by Rhuagh** [comment] 2018-04-16 20:27
Possibly, I don't get garbage though, I just get a black background.

**Comment by francesca64** [comment] 2018-06-02 12:27
I encounter the same problem in my own gfx app, and only on macOS (so I like to believe my resize math isn't the problem). It's even worse when switching to fullscreen. I believe this is a glutin bug.

Now that I have merge permission on glutin, I'd like to fix some of the especially troublesome long-standing bugs, like this and #547. It's just that first I have to fix the regressions people are reporting in winit 0.15.

**Comment by francesca64** [comment] 2018-06-04 15:58
My attempts to fix glutin bugs have been going very badly so far. One was a user error, another was a winit bug, and as for this one...

Please consult the triangle example: https://github.com/gfx-rs/gfx/blob/pre-ll/examples/triangle/main.rs#L97

You need to resize the context before you [update the views](https://github.com/amethyst/amethyst/blob/2716aefdf51c397c0be8432357eeb3df62140294/amethyst_renderer/src/pipe/target.rs#L109). That should fix both this and #547.

**Comment by Xaeroxe** [comment] 2018-06-04 16:03
Thank you!

**Closed** 2018-06-05 08:22 UTC
Labels: diff: medium, pri: important, project: rendering, type: bug
