### ISSUE TITLE
Project template fails to build

### ISSUE THREAD

**Issue by assumptionsoup** [amethyst/amethyst#188] opened 2017-02-14 20:37 UTC
>\> $ cargo run
>     Updating registry `https://github.com/rust-lang/crates.io-index`
>    Compiling bitflags v0.7.0
>    Compiling gfx_core v0.5.1
>    Compiling gfx_core v0.6.0
>    Compiling xml-rs v0.3.6
>    Compiling gl_generator v0.5.2
>    Compiling gfx_gl v0.3.1
>    Compiling glutin v0.7.4
>    Compiling gfx_device_dx11 v0.4.0
>    Compiling gfx v0.14.0
>    Compiling gfx_device_gl v0.13.0
>    Compiling gfx_window_dxgi v0.5.0
>    Compiling gfx_window_glutin v0.14.0
>    Compiling amethyst_renderer v0.4.1
> error[E0412]: type name `ColorFormat` is undefined or not in scope
>    --> C:\Users\jordan\.cargo\registry\src\github.com-1ecc6299db9ec823\amethyst_renderer-0.4.1\src\pass\deferred.rs:261:31
>     |
> 261 |         out: gfx::BlendTarget<ColorFormat> = ("o_Color", gfx::state::MASK_ALL, gfx::preset::blend::MULTIPLY),
>     |                               ^^^^^^^^^^^ undefined or not in scope
>     |
>     = help: you can import it into scope: `use target::ColorFormat;`.
> 
> error[E0412]: type name `ColorFormat` is undefined or not in scope
>    --> C:\Users\jordan\.cargo\registry\src\github.com-1ecc6299db9ec823\amethyst_renderer-0.4.1\src\pass\deferred.rs:261:31
>     |
> 261 |         out: gfx::BlendTarget<ColorFormat> = ("o_Color", gfx::state::MASK_ALL, gfx::preset::blend::MULTIPLY),
>     |                               ^^^^^^^^^^^ undefined or not in scope
>     |
>     = help: you can import it into scope: `use target::ColorFormat;`.
> 
> error[E0412]: type name `ColorFormat` is undefined or not in scope
>    --> C:\Users\jordan\.cargo\registry\src\github.com-1ecc6299db9ec823\amethyst_renderer-0.4.1\src\pass\deferred.rs:261:31
>     |
> 261 |         out: gfx::BlendTarget<ColorFormat> = ("o_Color", gfx::state::MASK_ALL, gfx::preset::blend::MULTIPLY),
>     |                               ^^^^^^^^^^^ undefined or not in scope
>     |
>     = help: you can import it into scope: `use target::ColorFormat;`.
> 
> error[E0412]: type name `ColorFormat` is undefined or not in scope
>    --> C:\Users\jordan\.cargo\registry\src\github.com-1ecc6299db9ec823\amethyst_renderer-0.4.1\src\pass\deferred.rs:261:31
>     |
> 261 |         out: gfx::BlendTarget<ColorFormat> = ("o_Color", gfx::state::MASK_ALL, gfx::preset::blend::MULTIPLY),
>     |                               ^^^^^^^^^^^ undefined or not in scope
>     |
>     = help: you can import it into scope: `use target::ColorFormat;`.
> 
> error[E0412]: type name `ColorFormat` is undefined or not in scope
>    --> C:\Users\jordan\.cargo\registry\src\github.com-1ecc6299db9ec823\amethyst_renderer-0.4.1\src\pass\deferred.rs:422:28
>     |
> 422 |     out: gfx::RenderTarget<ColorFormat> = "o_Color",
>     |                            ^^^^^^^^^^^ undefined or not in scope
>     |
>     = help: you can import it into scope: `use target::ColorFormat;`.
> 
> error[E0412]: type name `ColorFormat` is undefined or not in scope
>    --> C:\Users\jordan\.cargo\registry\src\github.com-1ecc6299db9ec823\amethyst_renderer-0.4.1\src\pass\deferred.rs:422:28
>     |
> 422 |     out: gfx::RenderTarget<ColorFormat> = "o_Color",
>     |                            ^^^^^^^^^^^ undefined or not in scope
>     |
>     = help: you can import it into scope: `use target::ColorFormat;`.
> 
> error[E0412]: type name `ColorFormat` is undefined or not in scope
>    --> C:\Users\jordan\.cargo\registry\src\github.com-1ecc6299db9ec823\amethyst_renderer-0.4.1\src\pass\deferred.rs:422:28
>     |
> 422 |     out: gfx::RenderTarget<ColorFormat> = "o_Color",
>     |                            ^^^^^^^^^^^ undefined or not in scope
>     |
>     = help: you can import it into scope: `use target::ColorFormat;`.
> 
> error[E0412]: type name `ColorFormat` is undefined or not in scope
>    --> C:\Users\jordan\.cargo\registry\src\github.com-1ecc6299db9ec823\amethyst_renderer-0.4.1\src\pass\deferred.rs:422:28
>     |
> 422 |     out: gfx::RenderTarget<ColorFormat> = "o_Color",
>     |                            ^^^^^^^^^^^ undefined or not in scope
>     |
>     = help: you can import it into scope: `use target::ColorFormat;`.
> 
> error: aborting due to 8 previous errors
> 
> error: Could not compile `amethyst_renderer`.
> 
> To learn more, run the command again with --verbose.

Despite what the compiler suggestion says, `use target::ColorFormat` is already defined AFAICT.

**Comment by ebkalderon** [comment] 2017-02-14 20:58
@assumptionsoup Hey there, thanks for reporting this issue! The definitions for `ColorFormat` and `DepthFormat` should be determined at compile time depending on which [Cargo features](http://doc.crates.io/manifest.html#the-features-section) are enabled in your `Cargo.toml`. Perhaps you have both the `"opengl"` and `"direct3d"` features enabled at the same time?

**Comment by nchashch** [comment] 2017-02-15 11:38
I couldn't reproduce this. `ColorFormat` and `DepthFormat` types are the same for all backends, so I don't think the problem is with features/backend choice.

Try deleting `Cargo.lock` file, maybe an old version of `gfx` is used and `amethyst_renderer` breaks because of that.

**Comment by assumptionsoup** [comment] 2017-02-15 20:53
I did some more testing.  This time, I've completely deleted and refetched the demo for each test.  I'm on windows.  In order to use the `--template` flag, I have to use the rust nightlies - it doesn't exist in beta or stable on windows (this might be different for other platforms??): 
```
$ rustup default nightly
info: using existing install for 'nightly-x86_64-pc-windows-msvc'
info: default toolchain set to 'nightly-x86_64-pc-windows-msvc'
```
Running the nightly version of rust produces a different error:

```
$ cargo run
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling gcc v0.3.43
   Compiling bitflags v0.7.0
   Compiling winapi v0.2.8
   Compiling fnv v1.0.5
   Compiling wavefront_obj v5.0.0
   Compiling num-traits v0.1.36
   Compiling mopa v0.2.2
   Compiling threadpool v1.3.2
   Compiling gdi32-sys v0.1.1
   Compiling khronos_api v1.0.0
   Compiling approx v0.1.1
   Compiling atom v0.3.4
   Compiling xml-rs v0.3.6
   Compiling dds-rs v0.4.0
   Compiling lazy_static v0.2.2
   Compiling libc v0.2.20
   Compiling yaml-rust v0.3.5
   Compiling tuple_utils v0.2.0
   Compiling num_cpus v1.2.1
   Compiling rand v0.3.15
   Compiling winapi-build v0.1.1
   Compiling bitflags v0.6.0
   Compiling log v0.3.6
   Compiling num-integer v0.1.32
   Compiling draw_state v0.6.0
   Compiling shared_library v0.1.5
   Compiling d3d11-sys v0.2.0
   Compiling shell32-sys v0.1.1
   Compiling d3dcompiler-sys v0.2.0
   Compiling kernel32-sys v0.2.2
   Compiling user32-sys v0.1.2
   Compiling gfx_core v0.5.1
   Compiling gfx_core v0.6.0
   Compiling num-iter v0.1.32
   Compiling dwmapi-sys v0.1.0
   Compiling rustc-serialize v0.3.22
   Compiling miniz-sys v0.1.9
   Compiling gl_generator v0.5.2
   Compiling amethyst_config v0.2.1
   Compiling flate2 v0.2.17
   Compiling imagefmt v4.0.0
   Compiling glutin v0.7.4
   Compiling gfx_gl v0.3.1
   Compiling num-complex v0.1.35
   Compiling num-bigint v0.1.35
   Compiling cgmath v0.12.0
   Compiling num-rational v0.1.35
   Compiling num v0.1.36
   Compiling cgmath v0.7.0
   Compiling genmesh v0.4.1
   Compiling gfx_device_gl v0.13.0
   Compiling gfx v0.14.0
   Compiling dxguid-sys v0.2.0
   Compiling time v0.1.36
   Compiling winit v0.5.11
   Compiling gfx_device_dx11 v0.4.0
   Compiling pulse v0.5.3
   Compiling specs v0.7.1
   Compiling gfx_window_dxgi v0.5.0
   Compiling gfx_window_glutin v0.14.0
   Compiling amethyst_renderer v0.4.1
   Compiling amethyst v0.4.1
   Compiling mygame v0.1.0 (file:///C:/Users/jordan/work/src/rust/mygame)
    Finished dev [unoptimized + debuginfo] target(s) in 85.79 secs
     Running `target\debug\mygame.exe`
thread 'main' panicked at 'attempt to subtract with overflow', <gfx_impl_struct_meta macros>:26
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: process didn't exit successfully: `target\debug\mygame.exe` (exit code: 101)
```
I also get this error on the beta channel `beta-x86_64-pc-windows-msvc unchanged - rustc 1.16.0-beta.1 (5276ba72e 2017-01-31)`.

If I switch back to rust stable:
```
$ rustup default stable
info: using existing install for 'stable-x86_64-pc-windows-msvc'
info: default toolchain set to 'stable-x86_64-pc-windows-msvc'

  stable-x86_64-pc-windows-msvc unchanged - rustc 1.14.0 (e8a012324 2016-12-16)
```
It produces the `ColorFormat` errors I originally posted.

**Comment by assumptionsoup** [comment] 2017-02-15 20:59
Full backtrace of the new panic on nightly/beta rust if it helps:
```
jordan@DESKTOP-OGTA9S6 MINGW64 ~/work/src/rust/mygame (master)
$ export RUST_BACKTRACE=1

jordan@DESKTOP-OGTA9S6 MINGW64 ~/work/src/rust/mygame (master)
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target\debug\mygame.exe`
thread 'main' panicked at 'attempt to subtract with overflow', <gfx_impl_struct_meta macros>:26
stack backtrace:
   0:     0x7ff6d7597fb8 - std::panicking::default_hook::{{closure}}
                        at C:\bot\slave\beta-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:356
   1:     0x7ff6d75974c4 - std::panicking::default_hook
                        at C:\bot\slave\beta-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:367
   2:     0x7ff6d759ae7d - std::panicking::rust_panic_with_hook
                        at C:\bot\slave\beta-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:555
   3:     0x7ff6d759ad18 - std::panicking::begin_panic<collections::string::String>
                        at C:\bot\slave\beta-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:517
   4:     0x7ff6d759ac34 - std::panicking::begin_panic_fmt
                        at C:\bot\slave\beta-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:501
   5:     0x7ff6d759abc9 - std::panicking::rust_begin_panic
                        at C:\bot\slave\beta-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:477
   6:     0x7ff6d75a2287 - core::panicking::panic_fmt
                        at C:\bot\slave\beta-dist-rustc-win-msvc-64\build\src\libcore\panicking.rs:69
   7:     0x7ff6d75a21cc - core::panicking::panic
                        at C:\bot\slave\beta-dist-rustc-win-msvc-64\build\src\libcore\panicking.rs:49
   8:     0x7ff6d747e901 - amethyst_renderer::pass::deferred::{{impl}}::query
                        at C:\Users\jordan\.cargo\registry\src\github.com-1ecc6299db9ec823\amethyst_renderer-0.4.1\src\pass\deferred.rs:10
   9:     0x7ff6d7446398 - gfx::pso::buffer::{{impl}}::link_input<amethyst_renderer::pass::deferred::Vertex,[(); 0]>
                        at C:\Users\jordan\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-0.14.0\src\pso\buffer.rs:95
  10:     0x7ff6d74a201e - amethyst_renderer::pass::deferred::blit::{{impl}}::link_to
                        at C:\Users\jordan\.cargo\registry\src\github.com-1ecc6299db9ec823\amethyst_renderer-0.4.1\src\pass\deferred.rs:419
  11:     0x7ff6d725eaa1 - gfx::factory::FactoryExt::create_pipeline_from_program<gfx_device_gl::factory::Factory,gfx_device_gl::Resources,amethyst_renderer::pass::deferred::blit::Init>
                        at C:\Users\jordan\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-0.14.0\src\factory.rs:239
  12:     0x7ff6d7259c42 - gfx::factory::FactoryExt::create_pipeline_state<gfx_device_gl::factory::Factory,gfx_device_gl::Resources,amethyst_renderer::pass::deferred::blit::Init>
                        at C:\Users\jordan\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-0.14.0\src\factory.rs:222
  13:     0x7ff6d725c4d1 - gfx::factory::FactoryExt::create_pipeline_simple<gfx_device_gl::factory::Factory,gfx_device_gl::Resources,amethyst_renderer::pass::deferred::blit::Init>
                        at C:\Users\jordan\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-0.14.0\src\factory.rs:252
  14:     0x7ff6d72df585 - amethyst_renderer::pass::deferred::BlitLayer<gfx_device_gl::Resources>::new<gfx_device_gl::Resources,gfx_device_gl::factory::Factory>
                        at C:\Users\jordan\.cargo\registry\src\github.com-1ecc6299db9ec823\amethyst_renderer-0.4.1\src\pass\deferred.rs:497
  15:     0x7ff6d72d3ee6 - amethyst_renderer::Renderer<gfx_device_gl::Resources, gfx_device_gl::command::CommandBuffer>::load_all<gfx_device_gl::Resources,gfx_device_gl::command::CommandBuffer,gfx_device_gl::factory::Factory>
                        at C:\Users\jordan\.cargo\registry\src\github.com-1ecc6299db9ec823\amethyst_renderer-0.4.1\src\lib.rs:69
  16:     0x7ff6d73615bf - amethyst::gfx_device::video_init::new_gl
                        at C:\Users\jordan\.cargo\registry\src\github.com-1ecc6299db9ec823\amethyst-0.4.1\src\gfx_device\video_init.rs:61
  17:     0x7ff6d7360f62 - amethyst::gfx_device::video_init::video_init
                        at C:\Users\jordan\.cargo\registry\src\github.com-1ecc6299db9ec823\amethyst-0.4.1\src\gfx_device\video_init.rs:11
  18:     0x7ff6d721de18 - amethyst::engine::app::Application::new<mygame::HelloWorld>
                        at C:\Users\jordan\.cargo\registry\src\github.com-1ecc6299db9ec823\amethyst-0.4.1\src\engine\app.rs:42
  19:     0x7ff6d720009b - amethyst::engine::app::ApplicationBuilder<mygame::HelloWorld>::done<mygame::HelloWorld>
                        at C:\Users\jordan\.cargo\registry\src\github.com-1ecc6299db9ec823\amethyst-0.4.1\src\engine\app.rs:228
  20:     0x7ff6d7226904 - mygame::main
                        at C:\Users\jordan\work\src\rust\mygame\src\main.rs:28
  21:     0x7ff6d759bd31 - panic_unwind::__rust_maybe_catch_panic
                        at C:\bot\slave\beta-dist-rustc-win-msvc-64\build\src\libpanic_unwind\lib.rs:98
  22:     0x7ff6d759b13a - std::rt::lang_start
                        at C:\bot\slave\beta-dist-rustc-win-msvc-64\build\src\libstd\rt.rs:51
  23:     0x7ff6d7226a2b - main
  24:     0x7ff6d75bc3e8 - __scrt_common_main_seh
                        at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  25:     0x7ffc254d8363 - BaseThreadInitThunk
error: process didn't exit successfully: `target\debug\mygame.exe` (exit code: 101)
```

**Comment by ebkalderon** [comment] 2017-02-16 04:18
Hmm, perhaps this is a weird driver bug on Windows? The issue appears to occur inside of `gfx` itself, and seems to involve calls to `create_pipeline_simple()`. @kvark and @msiglreith, what do you make of this?

**Comment by kvark** [comment] 2017-02-16 06:44
@ebkalderon this looks like https://github.com/gfx-rs/gfx/issues/1017
We basically just need to initialize the base pointer to 1 instead of leaving it random.

**Comment by kvark** [comment] 2017-02-16 07:20
Let us know if https://github.com/gfx-rs/gfx/pull/1189 helps, we can publish a patch to v0.14

**Comment by mdenchev** [comment] 2017-02-23 15:56
@assumptionsoup I get the same errors as you but compiling with the nightly gnu compiler worked for me.

**Comment by torkleyy** [comment] 2017-03-09 13:54
@assumptionsoup 
@mdenchev 

Does it work with latest stable and latest amethyst now?

**Comment by torkleyy** [comment] 2017-09-01 06:13
As it says in the Pull Request ( #196 ), this problem has been resolved by a updating the Rust version.

**Closed by torkleyy** 2017-09-01 06:13 UTC
Labels: diff: easy, pri: normal, type: bug
