### ISSUE TITLE
WASM: Investigate how to implement asset loading

### ISSUE THREAD

**Issue by azriel91** [amethyst/amethyst#2180] opened 2020-03-20 19:01 UTC
Currently when running [`pong_wasm`](https://github.com/amethyst/pong_wasm) as a WASM application, the application doesn't get past the `application_root_dir()` call. Understandably because that queries the execution environment in regards to the file system.

As a "get it done quickly but simply and cleanly" measure, place the existing functionality behind a `#[cfg(not(feature = "wasm"))]` directive, and for `#[cfg(feature = "wasm")]` allow `application_root_dir` and `loader.load` to return / take in URLs to assets.

The output of this ticket is not to *implement* said work, but discover enough information for what needs to be done, and to create issues for each part. One such part is #2177.

cc: @chemicstry

**Comment by chemicstry** [comment] 2020-03-20 19:34
I thought about multiple approaches and realised that almost none of the browsers support HTTP fetch from web worker. So asset fetch has to be done in the main thread and then (if that's needed/feasible) format import could be done in web worker (threadpool). What is the way to implement this I still don't know. Maybe store a list of pending assets and poll it on each frame? Any solution that I can think of doesn't integrate nicely into existing architecture. Worst case we can compile assets into a binary as was suggested in discord until atelier is integrated.

**Comment by azriel91** [comment] 2020-03-21 00:22
Thanks for looking into that -- has already saved much time going down a dead-end path :construction:.

I'm wondering if the solution posted by [SO: Make HTTP request inside Web Worker](https://stackoverflow.com/questions/30387469/make-http-request-inside-web-worker) is feasible for us -- [`node-worker-farm`](https://github.com/rvagg/node-worker-farm) uses `child_process`es to do it. https://github.com/rvagg/node-worker-farm/pull/90 adds support for threads, and transferring data between threads (but I haven't understood whether it still supports HTTP requests).

Otherwise am okay with settling for loading the assets on the main thread -- trying to resist inlining the assets into the binary, as that means existing Amethyst applications that discover assets at runtime won't be able to switch over easily.

**Comment by minecrawler** [comment] 2020-03-22 02:39
JS is very event based, so Amethyst would not load assets on the main thread in a blocking fashion, but instead kick off the loading only. The actual loading happens in the background. Amethyst could check the status between frames and handle assets regularly otherwise (as if they were downloaded by a loader thread).

The node worker farm is no solution, because it relies on NodeJS, which is not available in a browser.

**Comment by azriel91** [comment] 2020-03-22 05:37
Oh yes, @chemicstry helped me realize the error of my ways on discord :stuck_out_tongue:, and also got a POC working with XHRs -- #2182:

![image](https://user-images.githubusercontent.com/2993230/77243129-56b19300-6c6b-11ea-95a4-03db9d35714c.png)

**Comment by chemicstry** [comment] 2020-03-24 23:03
This still needs investigation because #2182 implementation causes spurious errors. Either `RuntimeError: memory access out of bounds` or `RuntimeError: operation does not support unaligned accesses`. Could be caused by the unlucky combination of `web_worker`, `SharedArrayBuffer` and synchronous `XmlHttpRequest`.

**Comment by azriel91** [comment] 2020-04-11 04:37
Do the spurious errors still happen on the latest pong_wasm?
I can't get any crashes now, and when I could, the browser tab just died so there's no logs / stack traces to go by.

If we can't reproduce the errors, then perhaps we should close this.

**Comment by chemicstry** [comment] 2020-04-11 11:26
Yeah they still happen on windows. I think we can close this since implementation is done. The #2228 will be open to investigate these spurious errors.

**Closed by chemicstry** 2020-04-11 11:26 UTC
Labels: feat: WASM support, status: ready
