### ISSUE TITLE
glTF loader swapping materials and transform when loading multiple objects

### ISSUE THREAD

**Issue by Frizi** [amethyst/amethyst#802] opened 2018-06-23 17:29 UTC
It seems that glTF loader is randomly reordering materials and transforms of objects that are loaded at the same time. The provided repo contains three objects in two files:

- question.gtfs
  - a blue question mark
- cylinder_stage.gltf
  - a red cylinder
  - a green "floor" plane

When loading the scene from prefab, the cylinder is pretty much always coming up as blue. Often it's loaded way too big. The floor is often misplaced or missing. The behaviour seems random - every execution can yield different results.

Repository with reproduction: https://github.com/Frizi/random_towers/tree/gltf-bug-repro

The reproduction branch contains precompiled glTFs, it should be ready to just `cargo run`. The models are exported using official glTF blender exporter. The original source `.blend` files are also provided in the repo.

**Comment by Rhuagh** [comment] 2018-09-03 04:39
Amethyst don't touch the matrix data, it just loads it. Are the models available somewhere?

**Comment by virome** [comment] 2018-09-04 04:04
I think I've found the source of the randomness:
When adding processing skins, amethyst loops over skin_map [here](https://github.com/amethyst/amethyst/blob/f6cbdfe6e5c38838190e59a35b6e6d35115af0cb/amethyst_gltf/src/format/mod.rs#L225) to load each skin. (I think) Rust hashmaps iterate in arbitrary/random order, and both `load_skin` calls set the Prefab.skinnable.joint (here)[https://github.com/amethyst/amethyst/blob/f6cbdfe6e5c38838190e59a35b6e6d35115af0cb/amethyst_gltf/src/format/skin.rs#L39]
So whichever skin is last in the random skin_map loop gets set.

**Comment by Rhuagh** [comment] 2018-09-04 05:54
So, yeah, the issue is that an entity can only belong to a single skin atm, simply because I've never seen a use case where that wasn't true. This will require a little bit of redesign of how we handle skins.

**Comment by jojolepro** [comment] 2018-09-15 20:00
for some reason I thought #933 was merged :P

**Closed** 2018-09-19 00:49 UTC
Labels: pri: important, project: gltf, type: bug
